# Generated by Django 4.1.7 on 2023-04-26 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_orderitem_product_alter_product_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
