# Generated by Django 4.1.7 on 2023-04-26 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_orderitem_product_alter_product_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=32, primary_key=True, serialize=False
            ),
        ),
    ]
