# Generated by Django 4.1.7 on 2023-04-26 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_cart_temp_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="id",
        ),
        migrations.AlterField(
            model_name="cart",
            name="temp_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
